# We'll start from a ubuntu xenial
FROM php:7.3-fpm-stretch



# Timezone
RUN rm /etc/localtime
RUN ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime

RUN apt-get update && \
  apt-get install --no-install-recommends -y \
  software-properties-common \
  wget \
  acl \
  apt-transport-https \
  lsb-release \
  sudo \
  locales \
  vim \
  git \
  optipng \
  jpegoptim \
  libpng-dev \
  libzip-dev \
  libcurl4-gnutls-dev \
  zlib1g-dev \
  libicu-dev \
  g++ \
  libxml2-dev \
  libmemcached-dev

RUN docker-php-ext-install gd \
    curl \
    intl \
    json \
    mbstring \
    xml \
    zip \
    bcmath \
    soap \
    pdo_mysql \
    sockets

RUN pecl install mongodb \
    memcached \
    redis

RUN echo "/usr/local/etc/php/conf.d/memcached.ini" > /usr/local/etc/php/conf.d/memcached.ini

# Install Composer
RUN curl -sS https:/getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN mkdir -p /var/www/.composer
RUN chmod -Rf 777 /var/www/.composer